"""Unit tests for AI/API Hub domain models, project scope semantics, and cost policy."""

from app.ai.hub.models import (
    ModelDescriptor,
    ProjectScope,
    UserAIProfile,
    UserCredential,
    evaluate_cost_policy,
)
from app.ai.hub.types import (
    CostPolicy,
    CostTier,
    CredentialHealth,
    CredentialTier,
    ModelCapability,
    ProviderType,
    ScopeType,
)


def test_project_scope_unverified_never_provably_independent():
    """Verify that UNVERIFIED_UNIQUE and USER_DECLARED_PROJECT scopes are NEVER treated as proof of quota independence."""
    # Synthetic scopes generated by system
    synth_a = ProjectScope(
        scope_id="synth_key_a", scope_type=ScopeType.UNVERIFIED_UNIQUE, verified=False
    )
    synth_b = ProjectScope(
        scope_id="synth_key_b", scope_type=ScopeType.UNVERIFIED_UNIQUE, verified=False
    )

    # Different IDs, but unverified -> CANNOT prove independence
    assert not synth_a.is_provably_independent(synth_b)
    assert not synth_b.is_provably_independent(synth_a)

    # User declared scopes (e.g. user typed "Project A" and "Project B")
    user_decl_a = ProjectScope(
        scope_id="Project A", scope_type=ScopeType.USER_DECLARED_PROJECT, verified=False
    )
    user_decl_b = ProjectScope(
        scope_id="Project B", scope_type=ScopeType.USER_DECLARED_PROJECT, verified=False
    )

    # Different IDs, but user-declared -> CANNOT prove independence
    assert not user_decl_a.is_provably_independent(user_decl_b)
    assert not user_decl_a.is_provably_independent(synth_a)


def test_project_scope_verified_establishes_genuine_boundary():
    """Verify that only provider-verified scopes establish genuine quota independence."""
    verified_proj_1 = ProjectScope(
        scope_id="gcp-project-100", scope_type=ScopeType.VERIFIED_PROJECT, verified=True
    )
    verified_proj_2 = ProjectScope(
        scope_id="gcp-project-200", scope_type=ScopeType.VERIFIED_PROJECT, verified=True
    )
    verified_proj_1_clone = ProjectScope(
        scope_id="gcp-project-100", scope_type=ScopeType.VERIFIED_PROJECT, verified=True
    )

    # Different verified projects are provably independent
    assert verified_proj_1.is_provably_independent(verified_proj_2)
    assert verified_proj_2.is_provably_independent(verified_proj_1)

    # Same project is NOT independent
    assert not verified_proj_1.is_provably_independent(verified_proj_1_clone)


def test_project_scope_shares_known_scope():
    """Verify detection of explicitly identical scopes."""
    scope_a1 = ProjectScope(scope_id="project-shared", scope_type=ScopeType.USER_DECLARED_PROJECT)
    scope_a2 = ProjectScope(scope_id="project-shared", scope_type=ScopeType.USER_DECLARED_PROJECT)
    scope_b = ProjectScope(scope_id="project-other", scope_type=ScopeType.USER_DECLARED_PROJECT)

    assert scope_a1.shares_known_scope(scope_a2)
    assert not scope_a1.shares_known_scope(scope_b)


def test_cost_policy_free_only():
    """Verify FREE_ONLY allows strictly free resources and blocks paid or unknown resources."""
    # Free model on free credential -> ALLOWED
    res_free = evaluate_cost_policy(
        policy=CostPolicy.FREE_ONLY,
        allow_paid_fallback=False,
        model_tier=CostTier.FREE,
        credential_tier=CredentialTier.FREE_TIER,
    )
    assert res_free.allowed
    assert res_free.effective_tier == CostTier.FREE

    # Paid model -> BLOCKED
    res_paid = evaluate_cost_policy(
        policy=CostPolicy.FREE_ONLY,
        allow_paid_fallback=False,
        model_tier=CostTier.PAID,
        credential_tier=CredentialTier.FREE_TIER,
    )
    assert not res_paid.allowed
    assert res_paid.effective_tier == CostTier.PAID
    assert "violates FREE_ONLY policy" in (res_paid.rejection_reason or "")

    # Unknown model -> BLOCKED (defensively treated as PAID)
    res_unknown = evaluate_cost_policy(
        policy=CostPolicy.FREE_ONLY,
        allow_paid_fallback=False,
        model_tier=CostTier.UNKNOWN,
        credential_tier=CredentialTier.FREE_TIER,
    )
    assert not res_unknown.allowed
    assert res_unknown.effective_tier == CostTier.PAID

    # Free model on PAID_TIER credential -> BLOCKED
    res_paid_cred = evaluate_cost_policy(
        policy=CostPolicy.FREE_ONLY,
        allow_paid_fallback=False,
        model_tier=CostTier.FREE,
        credential_tier=CredentialTier.PAID_TIER,
    )
    assert not res_paid_cred.allowed


def test_cost_policy_free_preferred():
    """Verify FREE_PREFERRED respects allow_paid_fallback flag."""
    # Free model is always allowed
    res_free = evaluate_cost_policy(
        policy=CostPolicy.FREE_PREFERRED,
        allow_paid_fallback=False,
        model_tier=CostTier.FREE,
        credential_tier=CredentialTier.FREE_TIER,
    )
    assert res_free.allowed
    assert res_free.effective_tier == CostTier.FREE

    # Paid model when allow_paid_fallback=False -> BLOCKED
    res_paid_blocked = evaluate_cost_policy(
        policy=CostPolicy.FREE_PREFERRED,
        allow_paid_fallback=False,
        model_tier=CostTier.PAID,
        credential_tier=CredentialTier.PAID_TIER,
    )
    assert not res_paid_blocked.allowed
    assert "allowPaidFallback is disabled" in (res_paid_blocked.rejection_reason or "")

    # Paid model when allow_paid_fallback=True -> ALLOWED
    res_paid_allowed = evaluate_cost_policy(
        policy=CostPolicy.FREE_PREFERRED,
        allow_paid_fallback=True,
        model_tier=CostTier.PAID,
        credential_tier=CredentialTier.PAID_TIER,
    )
    assert res_paid_allowed.allowed
    assert res_paid_allowed.effective_tier == CostTier.PAID


def test_cost_policy_any_configured():
    """Verify ANY_CONFIGURED permits all configured resources."""
    res_free = evaluate_cost_policy(
        policy=CostPolicy.ANY_CONFIGURED,
        allow_paid_fallback=False,
        model_tier=CostTier.FREE,
        credential_tier=CredentialTier.FREE_TIER,
    )
    assert res_free.allowed

    res_paid = evaluate_cost_policy(
        policy=CostPolicy.ANY_CONFIGURED,
        allow_paid_fallback=False,
        model_tier=CostTier.PAID,
        credential_tier=CredentialTier.PAID_TIER,
    )
    assert res_paid.allowed


def test_model_descriptor_capability_satisfaction():
    """Verify capability subset matching on model descriptors."""
    model = ModelDescriptor(
        model_id="gemini-3.5-flash",
        provider=ProviderType.GEMINI,
        display_name="Gemini 3.5 Flash",
        capabilities={
            ModelCapability.STRUCTURED_OUTPUT,
            ModelCapability.LONG_CONTEXT,
            ModelCapability.FAST_INFERENCE,
        },
        context_window=1000000,
        cost_tier=CostTier.FREE,
    )

    # Subsets match
    assert model.satisfies_capabilities({ModelCapability.STRUCTURED_OUTPUT})
    assert model.satisfies_capabilities(
        {ModelCapability.STRUCTURED_OUTPUT, ModelCapability.LONG_CONTEXT}
    )

    # Missing capability does not match
    assert not model.satisfies_capabilities({ModelCapability.HIGH_REASONING})


def test_user_ai_profile_defaults():
    """Verify safe default settings on UserAIProfile."""
    profile = UserAIProfile(user_id="user_test_123")
    assert profile.cost_policy == CostPolicy.FREE_ONLY
    assert not profile.allow_paid_fallback
    assert profile.primary_provider == ProviderType.GEMINI
    assert profile.provider_priority == [
        ProviderType.GEMINI,
        ProviderType.OPENROUTER,
        ProviderType.GROQ,
    ]
    assert profile.task_routing == {}


def test_user_credential_instantiation():
    """Verify UserCredential instantiation with masked key and project scope."""
    scope = ProjectScope(scope_id="proj-user-1", scope_type=ScopeType.USER_DECLARED_PROJECT)
    cred = UserCredential(
        id="cred_gemini_01",
        user_id="user_test_123",
        provider=ProviderType.GEMINI,
        friendly_name="Personal Gemini",
        encrypted_api_key="v1:fake_iv:fake_tag:fake_cipher",
        masked_key="AIzaSy...4X9q",
        project_scope=scope,
        cost_tier=CredentialTier.FREE_TIER,
        health_status=CredentialHealth.HEALTHY,
    )
    assert cred.id == "cred_gemini_01"
    assert cred.masked_key == "AIzaSy...4X9q"
    assert cred.cost_tier == CredentialTier.FREE_TIER
    assert cred.is_active
    assert not cred.project_scope.verified
