"""Forensic audit validation tests for AI Hub routing, model fallback, quota scoping, and cursor pagination."""

from datetime import UTC, datetime
from unittest.mock import AsyncMock, MagicMock

import pytest

from app.ai.adapters.base import BaseProviderAdapter, T
from app.ai.errors import AIProviderError, AIRateLimitError
from app.ai.hub.models import (
    ExecutionRequest,
    ModelDescriptor,
    ProjectScope,
    UserAIProfile,
    UserCredential,
)
from app.ai.hub.orchestrator import AIOrchestrator
from app.ai.hub.router import AIRouter
from app.ai.hub.types import (
    AITaskType,
    CostPolicy,
    CostTier,
    CredentialHealth,
    CredentialTier,
    ModelCapability,
    ProviderType,
    ScopeType,
)
from app.db.repositories.ai_telemetry_repo import ai_telemetry_repo


class MockAdapter(BaseProviderAdapter):
    """Configurable mock adapter for routing and fallback tests."""

    def __init__(self, provider: ProviderType, models: list[ModelDescriptor]):
        self._provider = provider
        self._models = models

    @property
    def provider_type(self) -> ProviderType:
        return self._provider

    def get_supported_models(self) -> list[ModelDescriptor]:
        return self._models

    def classify_error(self, error: Exception, model: str) -> AIProviderError:
        if isinstance(error, AIProviderError):
            return error
        return AIProviderError(str(error), model=model)

    async def generate_text(
        self,
        model: str,
        prompt: str,
        system_instruction: str | None = None,
        temperature: float = 0.7,
        timeout: float = 30.0,
        **kwargs,
    ) -> str:
        return f"Generated by {model}"

    async def generate_structured(
        self,
        model: str,
        prompt: str,
        schema: type[T],
        system_instruction: str | None = None,
        temperature: float = 0.1,
        timeout: float = 30.0,
        **kwargs,
    ) -> tuple[str, T]:
        return ("{}", schema())

    async def embed(
        self,
        text: str,
        model: str | None = None,
        max_retries: int = 1,
        base_delay_seconds: float = 0.5,
        **kwargs,
    ) -> list[float]:
        return [0.1, 0.2, 0.3]


@pytest.fixture
def clean_telemetry():
    orig_in_mem = ai_telemetry_repo._in_memory
    ai_telemetry_repo._in_memory = True
    ai_telemetry_repo.clear_memory()
    yield
    ai_telemetry_repo.clear_memory()
    ai_telemetry_repo._in_memory = orig_in_mem


@pytest.mark.asyncio
async def test_preferred_credential_model_fallback_before_credential_fallback(clean_telemetry):
    """Invariant A & B: Transient 429 on preferred model falls back to adjacent model on the SAME credential."""
    router = AIRouter()
    orchestrator = AIOrchestrator(router=router)

    # Models: Model A and Model B both satisfy RESUME_TAILORING
    model_a = ModelDescriptor(
        model_id="gemini-3.5-flash",
        provider=ProviderType.GEMINI,
        display_name="Gemini 3.5 Flash",
        capabilities={ModelCapability.STRUCTURED_OUTPUT, ModelCapability.LONG_CONTEXT, ModelCapability.HIGH_REASONING},
        cost_tier=CostTier.FREE,
        default_priority=30,
    )
    model_b = ModelDescriptor(
        model_id="gemini-3.8-flash",
        provider=ProviderType.GEMINI,
        display_name="Gemini 3.8 Flash",
        capabilities={ModelCapability.STRUCTURED_OUTPUT, ModelCapability.LONG_CONTEXT, ModelCapability.HIGH_REASONING},
        cost_tier=CostTier.FREE,
        default_priority=40,
    )

    mock_gemini = MockAdapter(ProviderType.GEMINI, [model_a, model_b])
    orchestrator.register_adapter(mock_gemini)

    # Mock behavior: Model A encounters transient 429; Model B succeeds
    async def mock_generate(model: str, prompt: str, **kwargs):
        if model == "gemini-3.5-flash":
            # Transient per-minute rate limit (is_project_quota_exhausted=False)
            raise AIRateLimitError(
                "Transient 15 RPM rate limit",
                model=model,
                is_project_quota_exhausted=False,
                retry_after=60.0,
            )
        return "Success from Model B on same credential"

    mock_gemini.generate_text = AsyncMock(side_effect=mock_generate)

    scope_resume = ProjectScope(scope_id="proj_resume", scope_type=ScopeType.USER_DECLARED_PROJECT, verified=False)
    scope_sibling = ProjectScope(scope_id="proj_sibling", scope_type=ScopeType.USER_DECLARED_PROJECT, verified=False)

    cred_resume = UserCredential(
        id="cred_resume",
        user_id="user_test",
        provider=ProviderType.GEMINI,
        friendly_name="Resume and Cover letter",
        encrypted_api_key="enc_key_1",
        masked_key="key_1...",
        project_scope=scope_resume,
    )
    cred_sibling = UserCredential(
        id="cred_sibling",
        user_id="user_test",
        provider=ProviderType.GEMINI,
        friendly_name="QA COPILOT",
        encrypted_api_key="enc_key_2",
        masked_key="key_2...",
        project_scope=scope_sibling,
    )

    profile = UserAIProfile(
        user_id="user_test",
        cost_policy=CostPolicy.FREE_ONLY,
        task_routing={"resume_tailoring": "cred_resume"},
        credentials=[cred_sibling, cred_resume],  # cred_sibling is at index 0
    )

    req = ExecutionRequest(
        task=AITaskType.RESUME_TAILORING,
        user_id="user_test",
        prompt="Tailor resume",
    )

    resp = await orchestrator.execute(req, profile=profile)

    # Must stay on the SAME preferred credential, trying model_b
    assert resp.credential_id_used == "cred_resume"
    assert resp.model_used == "gemini-3.8-flash"
    assert len(resp.attempted_hops) == 2
    assert resp.attempted_hops[0]["model"] == "gemini-3.5-flash"
    assert resp.attempted_hops[0]["credential_id"] == "cred_resume"
    assert resp.attempted_hops[1]["model"] == "gemini-3.8-flash"
    assert resp.attempted_hops[1]["credential_id"] == "cred_resume"

    # Telemetry should record fallbackLevel = 1 (Model Fallback!)
    records = ai_telemetry_repo.list_executions("user_test")
    assert len(records) == 1
    assert records[0]["fallbackLevel"] == 1  # L1 Model Fallback on same credential
    assert records[0]["hopsCount"] == 2
    assert records[0]["credentialIdUsed"] == "cred_resume"
    assert records[0]["preferredRouteSkipped"] is False


@pytest.mark.asyncio
async def test_confirmed_project_quota_exhaustion_triggers_credential_fallback(clean_telemetry):
    """When confirmed project quota exhaustion occurs, project scope is pruned and credential fallback occurs."""
    router = AIRouter()
    orchestrator = AIOrchestrator(router=router)

    model_a = ModelDescriptor(
        model_id="gemini-3.5-flash",
        provider=ProviderType.GEMINI,
        display_name="Gemini 3.5 Flash",
        capabilities={ModelCapability.STRUCTURED_OUTPUT, ModelCapability.LONG_CONTEXT, ModelCapability.HIGH_REASONING},
        cost_tier=CostTier.FREE,
        default_priority=30,
    )
    model_b = ModelDescriptor(
        model_id="gemini-3.8-flash",
        provider=ProviderType.GEMINI,
        display_name="Gemini 3.8 Flash",
        capabilities={ModelCapability.STRUCTURED_OUTPUT, ModelCapability.LONG_CONTEXT, ModelCapability.HIGH_REASONING},
        cost_tier=CostTier.FREE,
        default_priority=40,
    )

    mock_gemini = MockAdapter(ProviderType.GEMINI, [model_a, model_b])
    orchestrator.register_adapter(mock_gemini)

    # Mock behavior: Model A encounters confirmed project daily quota exhaustion
    async def mock_generate(model: str, prompt: str, **kwargs):
        key = kwargs.get("api_key")
        if key == "enc_key_1":
            raise AIRateLimitError(
                "Daily project quota exceeded",
                model=model,
                is_project_quota_exhausted=True,  # Confirmed project quota!
            )
        return "Success from sibling credential key_2"

    mock_gemini.generate_text = AsyncMock(side_effect=mock_generate)

    scope_resume = ProjectScope(scope_id="proj_shared_1", scope_type=ScopeType.USER_DECLARED_PROJECT, verified=False)
    scope_sibling = ProjectScope(scope_id="proj_shared_2", scope_type=ScopeType.USER_DECLARED_PROJECT, verified=False)

    cred_resume = UserCredential(
        id="cred_resume",
        user_id="user_test",
        provider=ProviderType.GEMINI,
        friendly_name="Resume and Cover letter",
        encrypted_api_key="enc_key_1",
        decrypted_key="enc_key_1",
        masked_key="key_1...",
        project_scope=scope_resume,
    )
    cred_sibling = UserCredential(
        id="cred_sibling",
        user_id="user_test",
        provider=ProviderType.GEMINI,
        friendly_name="QA COPILOT",
        encrypted_api_key="enc_key_2",
        decrypted_key="enc_key_2",
        masked_key="key_2...",
        project_scope=scope_sibling,
    )

    profile = UserAIProfile(
        user_id="user_test",
        cost_policy=CostPolicy.FREE_ONLY,
        task_routing={"resume_tailoring": "cred_resume"},
        credentials=[cred_resume, cred_sibling],
    )

    req = ExecutionRequest(
        task=AITaskType.RESUME_TAILORING,
        user_id="user_test",
        prompt="Tailor resume",
    )

    resp = await orchestrator.execute(req, profile=profile)

    # Because cred_resume had confirmed project quota exhaustion, Model B on cred_resume was skipped
    # and cred_sibling was attempted and succeeded!
    assert resp.credential_id_used == "cred_sibling"
    assert len(resp.attempted_hops) == 2
    assert resp.attempted_hops[0]["credential_id"] == "cred_resume"
    assert resp.attempted_hops[1]["credential_id"] == "cred_sibling"

    records = ai_telemetry_repo.list_executions("user_test")
    assert len(records) == 1
    assert records[0]["fallbackLevel"] == 2  # L2 Credential Fallback
    assert records[0]["preferredRouteSkipped"] is True
    assert records[0]["preferredRouteSkipReason"] == "RATE_LIMITED_OR_FAILED"


def test_no_credential_array_index_bias():
    """Verify that credentials are not prioritized based on insertion index."""
    router = AIRouter()

    model = ModelDescriptor(
        model_id="gemini-3.5-flash",
        provider=ProviderType.GEMINI,
        display_name="Gemini 3.5 Flash",
        capabilities={ModelCapability.STRUCTURED_OUTPUT, ModelCapability.LONG_CONTEXT, ModelCapability.HIGH_REASONING},
        cost_tier=CostTier.FREE,
        default_priority=30,
    )

    mock_adapter = MockAdapter(ProviderType.GEMINI, [model])
    adapters = {ProviderType.GEMINI: mock_adapter}

    scope = ProjectScope(scope_id="scope_1", scope_type=ScopeType.UNVERIFIED_UNIQUE, verified=False)

    # Credential A is at index 0, but mapped to QA_COPILOT
    cred_qa = UserCredential(
        id="cred_qa",
        user_id="user_test",
        provider=ProviderType.GEMINI,
        friendly_name="QA COPILOT",
        encrypted_api_key="k1",
        masked_key="k1...",
        project_scope=scope,
    )
    # Credential B is at index 1, unmapped / general
    cred_general = UserCredential(
        id="cred_general",
        user_id="user_test",
        provider=ProviderType.GEMINI,
        friendly_name="General Gemini Key",
        encrypted_api_key="k2",
        masked_key="k2...",
        project_scope=scope,
    )

    profile = UserAIProfile(
        user_id="user_test",
        task_routing={"qa_copilot": "cred_qa"},
        credentials=[cred_qa, cred_general],  # QA is index 0
    )

    req = ExecutionRequest(
        task=AITaskType.RESUME_TAILORING,
        user_id="user_test",
        prompt="Resume tailoring",
    )

    candidates = router.resolve_candidates(req, profile=profile, registered_adapters=adapters)

    # General credential must be ranked BEFORE QA Copilot credential for Resume Tailoring
    assert len(candidates) >= 2
    assert candidates[0].credential_id == "cred_general"
    assert candidates[1].credential_id == "cred_qa"


@pytest.mark.asyncio
async def test_operation_id_correlation(clean_telemetry):
    """Verify operation_id correlates multiple requests in AI telemetry."""
    router = AIRouter()
    orchestrator = AIOrchestrator(router=router)

    model = ModelDescriptor(
        model_id="gemini-3.5-flash",
        provider=ProviderType.GEMINI,
        display_name="Gemini 3.5 Flash",
        capabilities={ModelCapability.STRUCTURED_OUTPUT, ModelCapability.LONG_CONTEXT, ModelCapability.HIGH_REASONING},
        cost_tier=CostTier.FREE,
        default_priority=30,
    )
    mock_adapter = MockAdapter(ProviderType.GEMINI, [model])
    orchestrator.register_adapter(mock_adapter)

    profile = UserAIProfile(user_id="user_op")
    shared_op_id = "op_batch_899"

    # Request 1: Resume Tailoring
    req1 = ExecutionRequest(
        task=AITaskType.RESUME_TAILORING,
        user_id="user_op",
        prompt="Task 1",
        operation_id=shared_op_id,
    )
    await orchestrator.execute(req1, profile=profile)

    # Request 2: Cover Letter
    req2 = ExecutionRequest(
        task=AITaskType.COVER_LETTER_GEN,
        user_id="user_op",
        prompt="Task 2",
        operation_id=shared_op_id,
    )
    await orchestrator.execute(req2, profile=profile)

    records = ai_telemetry_repo.list_executions("user_op")
    assert len(records) == 2
    assert records[0]["operationId"] == shared_op_id
    assert records[1]["operationId"] == shared_op_id


def test_cursor_pagination_telemetry(clean_telemetry):
    """Verify cursor-based pagination returns correct pages and next_cursor."""
    user_id = "user_page_test"

    # Seed 5 records with explicit timestamps
    for i in range(1, 6):
        ai_telemetry_repo.record_execution(
            user_id=user_id,
            record={
                "executionId": f"exec_{i}",
                "userId": user_id,
                "task": "resume_tailoring",
                "providerUsed": "GEMINI",
                "modelUsed": "gemini-3.5-flash",
                "credentialIdUsed": "cred_1",
                "success": True,
                "latencyMs": 100.0 * i,
                "fallbackLevel": 0,
                "hopsCount": 1,
                "timestamp": f"2026-10-05T10:0{i}:00+00:00",
            },
        )

    # Page 1: limit 2
    page1 = ai_telemetry_repo.list_executions_paginated(user_id, limit=2)
    assert len(page1["items"]) == 2
    assert page1["items"][0]["executionId"] == "exec_5"
    assert page1["items"][1]["executionId"] == "exec_4"
    assert page1["has_more"] is True
    assert page1["next_cursor"] == "2026-10-05T10:04:00+00:00"

    # Page 2: limit 2 with cursor from Page 1
    page2 = ai_telemetry_repo.list_executions_paginated(user_id, limit=2, cursor=page1["next_cursor"])
    assert len(page2["items"]) == 2
    assert page2["items"][0]["executionId"] == "exec_3"
    assert page2["items"][1]["executionId"] == "exec_2"
    assert page2["has_more"] is True
    assert page2["next_cursor"] == "2026-10-05T10:02:00+00:00"

    # Page 3: limit 2 with cursor from Page 2
    page3 = ai_telemetry_repo.list_executions_paginated(user_id, limit=2, cursor=page2["next_cursor"])
    assert len(page3["items"]) == 1
    assert page3["items"][0]["executionId"] == "exec_1"
    assert page3["has_more"] is False
    assert page3["next_cursor"] is None
