"""Structured Resume Schemas and Provenance Models adhering to SCHEMA.md."""

from datetime import UTC, datetime
from typing import Literal

from pydantic import BaseModel, Field


class ResumeContact(BaseModel):
    fullName: str
    email: str
    phone: str | None = None
    city: str | None = None
    country: str | None = "India"
    github: str | None = None
    linkedin: str | None = None
    portfolio: str | None = None


class ResumeBullet(BaseModel):
    text: str
    source_fact_ids: list[str] = Field(default_factory=list)


class ResumeSkillCategory(BaseModel):
    category: str
    items: list[str] = Field(default_factory=list)
    source_fact_ids: list[str] = Field(default_factory=list)


class ResumeExperienceItem(BaseModel):
    experience_fact_id: str | None = None
    company: str
    title: str
    location: str | None = None
    startDate: str | None = None
    endDate: str | None = None
    current: bool = False
    bullets: list[ResumeBullet] = Field(default_factory=list)


class ResumeProjectItem(BaseModel):
    project_fact_id: str | None = None
    name: str
    technologies: list[str] = Field(default_factory=list)
    url: str | None = None
    bullets: list[ResumeBullet] = Field(default_factory=list)


class ResumeEducationItem(BaseModel):
    education_fact_id: str | None = None
    institution: str
    degree: str
    field: str | None = None
    startDate: str | None = None
    endDate: str | None = None
    grade: str | None = None


class ResumeCourseCertificationItem(BaseModel):
    course_fact_id: str | None = None
    title: str
    completionYear: str | None = None
    certificateUrl: str | None = None
    description: str | None = None
    provider: str | None = None
    instructor: str | None = None


class ResumeJobAlignment(BaseModel):
    matched_skills: list[str] = Field(default_factory=list)
    transferable_strengths: list[str] = Field(default_factory=list)
    skill_gaps: list[str] = Field(default_factory=list)
    fit_summary: str | None = None


class StructuredResumeContent(BaseModel):
    """Authoritative structured resume payload generated by Gemini and validated deterministically."""

    personal: ResumeContact
    summary: str
    summary_fact_ids: list[str] = Field(default_factory=list)
    education: list[ResumeEducationItem] = Field(default_factory=list)
    skills: list[ResumeSkillCategory] = Field(default_factory=list)
    experience: list[ResumeExperienceItem] = Field(default_factory=list)
    projects: list[ResumeProjectItem] = Field(default_factory=list)
    course_certifications: list[ResumeCourseCertificationItem] = Field(default_factory=list)
    leadership: list[ResumeExperienceItem] = Field(default_factory=list)
    job_alignment: ResumeJobAlignment = Field(default_factory=ResumeJobAlignment)


class ResumeValidationResult(BaseModel):
    """Deterministic validation report with 0 AI cost."""

    is_valid: bool
    truth_score: int = Field(ge=0, le=100)
    verified_fact_count: int = 0
    violations: list[str] = Field(default_factory=list)
    truth_violations: list[str] = Field(default_factory=list)
    structural_violations: list[str] = Field(default_factory=list)
    transferable_highlights: list[str] = Field(default_factory=list)
    skill_gaps: list[str] = Field(default_factory=list)
    status: Literal["PASSED", "BLOCKED"] = "PASSED"


class TailorResumeRequest(BaseModel):
    job_id: str
    user_id: str | None = None
    custom_instructions: str | None = None


class ValidateAndRenderRequest(BaseModel):
    structured_content: StructuredResumeContent
    user_id: str | None = None


class TailoredResumeDTO(BaseModel):
    id: str
    userId: str
    jobId: str
    jobTitle: str
    jobCompany: str
    structuredContent: StructuredResumeContent
    validationResult: ResumeValidationResult
    latexCode: str
    createdAt: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())
    updatedAt: str = Field(default_factory=lambda: datetime.now(UTC).isoformat())
